#!/bin/bash

# ARGV=("$@")
# ARGC=("$#")

# if [ $ARGC -ne 2 ]; then
#     echo  "Invalid number of arguments, usage: build [gitlab_username] [gitlab_password]"
#     exit
# fi

# GITLAB_USERNAME=${ARGV[0]}
# GITLAB_PASSWORD=${ARGV[1]}

TAG=firehose:artifact
echo "Building the Docker image..."
sudo docker pull ubuntu:20.04
sudo docker build --build-arg ncpus=$(nproc) -f Dockerfile -t $TAG .
